version: "3"
services:
  postgres:
    image: postgres
## using env here is a must ! but since i won't deploy this project ...
    environment:
       POSTGRES_PASSWORD: drwx_anwar
       POSTGRES_USER: drwx_anwar
       POSTGRES_DB: am_faster_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: am_faster_backend
    ports:
      - 8000:8000
    restart: always 
## TODO : frontend container here
    
volumes:
  postgres_data:
