version: "3"
services:
  postgres:
    image: postgres
    environment:
       POSTGRES_PASSWORD: drwx_anwar
       POSTGRES_USER: drwx_anwar
       POSTGRES_DB: am_faster_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: am_faster_backend
    ports:
      - 8000:8000
    
volumes:
  postgres_data: