###
GET http://localhost:8000/invitations

###
POST http://localhost:8000/game
Content-Type: application/json

{
    "user_id":1 , "user_score" : 11 , "game_id" : 1
}

###
POST http://localhost:8000/challenges/new_challenge
Content-Type: application/json

{
    "text":"The Amazon rainforest, also known as the Amazon Jungle, is the largest tropical rainforest in the world. It is home to a vast array of plant and animal species." ,
    "difficulty" : "Hard",
    "category": "Nature"
}